swagger: "2.0"
info:
  description: "This is a banking service of crediting of users. Funds for lending are provided from the budget 517 000 UAH rate 30%"
  version: "1.4.0.8"
  title: "Banking service"
  termsOfService: "http://jmyh-banking.com"
  contact:
    email: "jmyhbanking@gmail.com"
host: "jmyh-banking.com"
tags:
- name: "account"
  description: "Everything for setting your account"
- name: "bank"
  description: "Everything for your money"
schemes:
- "https"
- "http"
paths:
  /account:
    post:
      tags:
      - "account"
      summary: "Create bank account"
      description: "This can only be done by the logged in user."
      operationId: "createUser"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        default:
          description: "successful operation"
  /account/login:
    get:
      tags:
      - "account"
      summary: "Logs user into the system"
      description: ""
      operationId: "loginUser"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "username"
        in: "query"
        required: true
        type: "string"
      - name: "password"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
          headers:
            X-Rate-Limit:
              type: "integer"
              format: "int32"
              description: "calls per hour allowed by the user"
            X-Expires-After:
              type: "string"
              format: "date-time"
              description: "date in UTC when token expires"
        400:
          description: "Invalid username/password supplied"
  /account/logout:
    get:
      tags:
      - "account"
      summary: "Logs out current logged in user session."
      description: ""
      operationId: "logoutUser"
      produces:
      - "application/xml"
      - "application/json"
      parameters: []
      responses:
        default:
          description: "successful operation"
    delete:
      tags:
      - "account"
      summary: "Delete user"
      description: "Delete user from the banking system."
      operationId: "deleteUser"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "The name that needs to be deleted"
        required: true
        type: "string"
      responses:
        400:
          description: "Invalid username supplied"
        404:
          description: "User not found"
  /bank:
    post:
      tags:
      - "bank"
      summary: "Information about credits"
      description: "Get actual information about loans of specific user"
      operationId: "getInformation"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/Credit"
      responses:
        default:
          description: "successful operation"
  /bank/loan:
    get:
      tags:
      - "bank"
      summary: "Gets credit"
      description: "Gets credit for a specific user account."
      operationId: "getCredit"
      produces:
      - "application/xml"
      - "application/json"
      parameters: 
      - name: "password"
        in: "query"
        description: "The password for login in clear text"
        required: true
        type: "string"
      - name: "creditAmount"
        in: "query"
        description: "pay off amount"
        type: "integer"
      
      responses:
        200:
          description: "successful operation"
        400:
            description: "Invalid password supplied or bank balance is less than the loan amount"
  /bank/payoff:
    get:
      tags:
      - "bank"
      summary: "Pays off credit"
      description: "Pays off credit for a specific user account."
      operationId: "payoffCredit"
      produces:
      - "application/xml"
      - "application/json"
      parameters: 
      - name: "password"
        in: "query"
        description: "The password for login in clear text"
        required: true
        type: "string"
      - name: "creditAmount"
        in: "query"
        description: "loan amount"
        type: "integer"
        
      responses:
        200:
          description: "successful operation"
        400:
            description: "Invalid password supplied or bank balance is less than the loan amount"
  
definitions:
  User:
    type: "object"
    properties:
      idUser:
        type: "integer"
        format: "int64"
      firstName:
        type: "string"
      lastName:
        type: "string"
      userEmail:
        type: "string"
      userPassword:
        type: "string"
        
  Credit:
    type: "object"
    properties:
      idCredit:
        type: "integer"
        format: "int64"
      idUser:
        type: "integer"
        format: "int64"
      creditAmount:
        type: "integer"
        format: "int64"
      date:
        type: "string"
        format: "int64"
      
  Bank:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      bankMoney:
        type: "integer"
        format: "int64"
    xml:
      name: "BankAccount"